import { Raleway } from "next/font/google"; 
import { CartProvider } from "./context/contextComponent";
import "./globals.css";


const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], // Pesos disponíveis
});

export const metadata = {
  title: "Grill Burgueria",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={raleway.variable}>
     <body>
        <CartProvider>
          {children}
        </CartProvider>
      </body>
    </html>
  );
}
